1. **Creation of NumPy Arrays:**
   - Creating arrays from Python lists: `np.array([1, 2, 3])`: Converts a Python list into a NumPy array.
   - Creating arrays with specific values: `np.zeros((3, 3))`, `np.ones((2, 2))`, `np.full((2, 2), 7)`: Creates arrays filled with zeros, ones, or a specified constant value.
   - Creating arrays with a range of values: `np.arange(0, 10, 2)`, `np.linspace(0, 1, 5)`: Generates arrays with evenly spaced values within a given range.

2. **Array Attributes:**
   - Getting the shape of an array: `array.shape`: Returns a tuple representing the dimensions of the array.
   - Getting the data type of elements in an array: `array.dtype`: Returns the data type of elements in the array.
   - Getting the number of dimensions: `array.ndim`: Returns the number of dimensions (axes) of the array.
   - Getting the total number of elements: `array.size`: Returns the total number of elements in the array.

3. **Array Indexing and Slicing:**
   - Accessing elements: `array[0]`, `array[-1]`: Accesses elements at specific indices in the array.
   - Slicing: `array[start:end]`, `array[:3]`, `array[2:]`: Extracts a subset of elements from the array.

4. **Element-wise Operations:**
   - Arithmetic operations: `array1 + array2`, `array1 * array2`, `array1 / array2`: Performs element-wise addition, multiplication, and division.
   - Broadcasting: `array1 + scalar`, `array1 * scalar`: Applies arithmetic operations between arrays and scalar values.

5. **Aggregation Functions:**
   - Sum of all elements: `np.sum(array)`: Computes the sum of all elements in the array.
   - Minimum and maximum elements: `np.min(array)`, `np.max(array)`: Finds the minimum and maximum elements in the array.
   - Mean and median: `np.mean(array)`, `np.median(array)`: Calculates the mean and median of the array.
   - Variance and standard deviation: `np.var(array)`, `np.std(array)`: Computes the variance and standard deviation of the array.

6. **Array Manipulation:**
   - Transposing: `array.T`: Transposes the array (rows become columns and vice versa).
   - Reshaping: `array.reshape((2, 3))`: Reshapes the array into a new shape.
   - Flattening: `array.flatten()`: Converts a multi-dimensional array into a 1D array.
   - Concatenation: `np.concatenate((array1, array2))`: Concatenates arrays along a specified axis.
   - Stacking: `np.vstack((array1, array2))`, `np.hstack((array1, array2))`: Stacks arrays vertically or horizontally.

7. **Array Comparison and Boolean Indexing:**
   - Element-wise comparison: `array1 > array2`, `array1 == array2`: Compares elements of two arrays element-wise.
   - Boolean indexing: `array[array > 0]`, `array[array % 2 == 0]`: Uses boolean arrays to index or filter elements.

8. **Linear Algebra Operations:**
   - Matrix multiplication: `np.dot(matrix1, matrix2)`: Computes the dot product of two matrices.
   - Matrix inverse: `np.linalg.inv(matrix)`: Computes the inverse of a square matrix.
   - Eigenvalues and eigenvectors: `np.linalg.eig(matrix)`: Computes the eigenvalues and eigenvectors of a matrix.
   - Singular Value Decomposition (SVD): `np.linalg.svd(matrix)`: Computes the singular value decomposition of a matrix.

9. **Random Number Generation:**
   - Generating random integers: `np.random.randint(0, 10, size=(2, 2))`: Generates random integers within a specified range.
   - Generating random samples from a uniform distribution: `np.random.rand(3, 3)`: Generates random samples from a uniform distribution over [0, 1).
   - Generating random samples from a normal distribution: `np.random.randn(3, 3)`: Generates random samples from a standard normal distribution.

10. **File Input/Output:**
    - Loading data from a text file: `np.loadtxt('data.txt')`: Loads data from a text file into an array.
    - Saving data to a text file: `np.savetxt('data.txt', array)`: Saves data from an array to a text file.

These explanations provide an overview of various basic operations that can be performed with NumPy arrays, along with their

### Creation of NumPy Arrays:

In [2]:
import numpy as np

# Creating arrays from Python lists
array1 = np.array([1, 2, 3])
print(array1)

# Creating arrays with specific values
array2 = np.zeros((3, 3))
print(array2)

array3 = np.ones((2, 2))
print(array3)

array4 = np.full((2, 2), 7)
print(array4)

# Creating arrays with a range of values
array5 = np.arange(0, 10, 2)
print(array5)

array6 = np.linspace(0, 1, 5)
print(array6)


[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Array Attributes

In [5]:
# Creating arrays from Python lists
array1 = np.array([1, 2, 3])
print(array1)

# Getting array shape
print(array1.shape)

# Getting data type of elements
print(array1.dtype)

# Getting number of dimensions
print(array1.ndim)

# Getting total number of elements
print(array1.size)


[1 2 3]
(3,)
int64
1
3


### Array Indexing and Slicing:


In [6]:
# Creating arrays from Python lists
array1 = np.array([1, 2, 3])
print(array1)

# Accessing elements
print(array1[0])

# Slicing
print(array1[:2])


[1 2 3]
1
[1 2]


### Element-wise Operations

In [8]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Arithmetic operations
print(array1 + array2)

# Broadcasting
print(array1 * 2)


[5 7 9]
[2 4 6]


### Aggregation Functions:


In [9]:
array1 = np.array([1, 2, 3])

# Sum of all elements
print(np.sum(array1))

# Minimum and maximum elements
print(np.min(array1), np.max(array1))

# Mean and median
print(np.mean(array1), np.median(array1))

# Variance and standard deviation
print(np.var(array1), np.std(array1))


6
1 3
2.0 2.0
0.6666666666666666 0.816496580927726


### Array Manipulation

In [12]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Transposing
print(array2.T)

# Reshaping
print(array1.reshape((1, 3)))

# Flattening
print(array1.flatten())

# Concatenation
print(np.concatenate((array1, array2)))

# Stacking
print(np.vstack((array1, array2)))


[4 5 6]
[[1 2 3]]
[1 2 3]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Array Comparison and Boolean Indexing:


In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise comparison
print(array1 > array2)

# Boolean indexing
print(array1[array1 > 2])


[False False False]
[3]


### Linear Algebra Operations:

In [14]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print(np.dot(matrix1, matrix2))

# Matrix inverse
print(np.linalg.inv(matrix1))

# Eigenvalues and eigenvectors
print(np.linalg.eig(matrix1))

# Singular Value Decomposition (SVD)
print(np.linalg.svd(matrix1))

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))


### Random Number Generation:

In [15]:
# Generating random integers
print(np.random.randint(0, 10, size=(2, 2)))

# Generating random samples from a uniform distribution
print(np.random.rand(3, 3))

# Generating random samples from a normal distribution
print(np.random.randn(3, 3))


[[5 5]
 [9 7]]
[[0.69047725 0.24239124 0.13392834]
 [0.57626633 0.60441647 0.21587822]
 [0.9918673  0.70408011 0.79488779]]
[[ 0.13989919 -1.03904664  0.16633068]
 [ 0.82946701  0.37510066  1.91786259]
 [ 0.87430558 -0.90482989 -0.44926989]]


### File Input/Output:

In [16]:
# Saving data to a text file
np.savetxt('data.txt', array1)

# Loading data from a text file
loaded_array = np.loadtxt('data.txt')
print(loaded_array)

[1. 2. 3.]


In [17]:
import numpy as np

# Sample array
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Saving data to a text file
np.savetxt('data1.txt', array1)

# Loading data from a text file
loaded_array = np.loadtxt('data1.txt')
print(loaded_array)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
