# Array Creation

## np.array(): Create an array from a list or array-like object.

In [4]:
import numpy as np

# Create an array from a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


## np.zeros(): Create an array filled with zeros

In [5]:
import numpy as np

# Create a 1D array filled with zeros
zeros_array = np.zeros(5)
print(zeros_array)

# Create a 2D array filled with zeros
zeros_2d_array = np.zeros((2, 3))
print(zeros_2d_array)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


## np.ones(): Create an array filled with ones

In [6]:
import numpy as np

# Create a 1D array filled with ones
ones_array = np.ones(5)
print(ones_array)

# Create a 2D array filled with ones
ones_2d_array = np.ones((2, 3))
print(ones_2d_array)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


## np.empty(): Create an uninitialized array

In [17]:
import numpy as np

# Create an uninitialized array of size 3
empty_array1 = np.empty(3)
empty_array2 = np.empty(2)
print(empty_array1)
print(empty_array2)


[3. 2. 1.]
[2.05833592e-312 2.33419537e-312]


## np.arange(): Create an array with evenly spaced values

In [18]:
import numpy as np

# Create an array with values from 0 to 9
range_array = np.arange(10)
print(range_array)

# Create an array with values from 1 to 10 with step 2
range_array_step = np.arange(1, 11, 2)
print(range_array_step)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## np.linspace(): Create an array with evenly spaced values over a specified range

In [19]:
import numpy as np

# Create an array with 5 values from 0 to 10
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)


[ 0.   2.5  5.   7.5 10. ]


## np.eye(): Create an identity matrix

In [20]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
