## Numpy Array Manipulation

## np.reshape(): Reshape an array

In [1]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


## np.concatenate(): Concatenate arrays along a specified axis

In [3]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenate along the first axis (rows)
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)


[[1 2]
 [3 4]
 [5 6]]


## np.split(): Split an array into multiple sub-arrays

In [4]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into three sub-arrays
sub_arrays = np.split(arr, 3)
print(sub_arrays)


[array([1, 2]), array([3, 4]), array([5, 6])]


## np.transpose(): Transpose an array

In [5]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2], [3, 4]])

# Transpose the array
transposed_arr = np.transpose(arr)
print(transposed_arr)


[[1 3]
 [2 4]]


## np.flatten(): Flatten a multi-dimensional array to a 1D array

In [6]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2], [3, 4]])

# Flatten the array
flattened_arr = arr.flatten()
print(flattened_arr)


[1 2 3 4]


## np.vstack(): Stack arrays vertically

In [7]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertically stack the arrays
stacked_arr = np.vstack((arr1, arr2))
print(stacked_arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## np.hstack(): Stack arrays horizontally

In [8]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Horizontally stack the arrays
stacked_arr = np.hstack((arr1, arr2))
print(stacked_arr)


[[1 2 5 6]
 [3 4 7 8]]
