# Numpy Random Number Generation

## np.random.rand(): Generate random numbers from a uniform distribution

In [1]:
import numpy as np

# Generate an array of random numbers between 0 and 1
random_numbers = np.random.rand(3, 3)
print(random_numbers)


[[0.50317348 0.2094243  0.77199942]
 [0.83486946 0.27321933 0.67771316]
 [0.95457741 0.87939882 0.44535895]]


## np.random.randn(): Generate random numbers from a standard normal distribution

In [2]:
import numpy as np

# Generate an array of random numbers from a standard normal distribution
random_numbers = np.random.randn(3, 3)
print(random_numbers)


[[-1.35992252 -0.25593733  0.00209538]
 [-0.75174622 -0.49144218  0.60903446]
 [ 0.92263911  0.05274315  0.7050096 ]]


## np.random.randint(): Generate random integers

In [3]:
import numpy as np

# Generate a random integer between 0 and 9
random_integer = np.random.randint(10)
print(random_integer)

# Generate an array of random integers between 0 and 9
random_integers = np.random.randint(0, 10, size=(3, 3))
print(random_integers)


5
[[4 7 3]
 [5 5 5]
 [3 6 8]]


## np.random.choice(): Generate random samples from a given 1-D array

In [4]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Generate a random sample from the array
random_sample = np.random.choice(arr)
print(random_sample)

# Generate a random sample of size 3 from the array
random_samples = np.random.choice(arr, size=3, replace=False)
print(random_samples)


2
[2 1 5]
