# Numpy Indexing

## np.newaxis: Insert a new axis into an array

In [1]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Insert a new axis to make it a 2D array
new_arr = arr[:, np.newaxis]
print(new_arr)


[[1]
 [2]
 [3]
 [4]
 [5]]


## np.take(): Return elements from an array at specified indices

In [2]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Return elements at specified indices
indices = [0, 2, 4]
taken_elements = np.take(arr, indices)
print(taken_elements)


[1 3 5]


## np.where(): Return the indices of elements that satisfy a condition

In [3]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Return the indices of elements greater than 3
indices = np.where(arr > 3)
print(indices)


(array([3, 4]),)


## np.argmax(): Find the indices of the maximum value along an axis.


In [4]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find the indices of the maximum value along the second axis
indices = np.argmax(arr, axis=1)
print(indices)


[2 2]
