## Numpy File Input/Output

## np.save(): Save an array to a binary file.


In [1]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Save the array to a binary file
np.save('array_data.npy', arr)


## np.load(): Load an array from a binary file.


In [2]:
import numpy as np

# Load the array from the binary file
loaded_arr = np.load('array_data.npy')
print(loaded_arr)


[1 2 3 4 5]


## np.savetxt(): Save an array to a text file.


In [3]:
import numpy as np

# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a text file
np.savetxt('array_data.txt', arr)


## np.loadtxt(): Load data from a text file.


In [4]:
import numpy as np

# Load data from the text file
loaded_data = np.loadtxt('array_data.txt')
print(loaded_data)


[[1. 2. 3.]
 [4. 5. 6.]]
